# pymeshlab's public names come from ``from .pmeshlab import *`` over a compiled extension, which no
# checker can read, and every ``MeshSet`` filter is bound at import from a runtime table
# (``bind_function``). This stub declares the four classes the test suite names; their members stay
# dynamic, as they are at runtime. Test-only: nothing under ``ordito/`` imports pymeshlab.
from typing import Any

class Mesh:
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class MeshSet:
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def add_mesh(self, mesh: Mesh, *args: object, **kwargs: object) -> None: ...
    def current_mesh(self) -> Mesh: ...
    def __getattr__(self, name: str) -> Any: ...

class PureValue:
    def __init__(self, value: float) -> None: ...

class PercentageValue:
    def __init__(self, value: float) -> None: ...
